 truncate  table MigracionMatriz ;
ALTER TABLE MigracionMatriz AUTO_INCREMENT = 1;
truncate  table HistoricoMigracion ;
ALTER TABLE HistoricoMigracion AUTO_INCREMENT = 1;
truncate  table RequisitosMatriz ;
ALTER TABLE RequisitosMatriz AUTO_INCREMENT = 1;
truncate  table RelacionHistoricos ;
ALTER TABLE RelacionHistoricos AUTO_INCREMENT = 1;
truncate  table temas_grupo ;
ALTER TABLE temas_grupo AUTO_INCREMENT = 1;
truncate  table normas ;
ALTER TABLE normas AUTO_INCREMENT = 1;
truncate  table Articulos ;
ALTER TABLE Articulos AUTO_INCREMENT = 1;
truncate  table Evaluacion ;
ALTER TABLE Evaluacion AUTO_INCREMENT = 1;
truncate  table EstadoCumplimiento ;
ALTER TABLE EstadoCumplimiento AUTO_INCREMENT = 1;
truncate  table Comentario ;
ALTER TABLE Comentario AUTO_INCREMENT = 1;
truncate table sub_factor_riesgo;
ALTER TABLE sub_factor_riesgo AUTO_INCREMENT = 1;
truncate table factor_riesgo;
ALTER TABLE factor_riesgo AUTO_INCREMENT = 1;
truncate table yearemision;
ALTER TABLE yearemision AUTO_INCREMENT = 1;
truncate table Relacionderogada;
ALTER TABLE Relacionderogada AUTO_INCREMENT = 1;
truncate table autoridademisora;
ALTER TABLE autoridademisora AUTO_INCREMENT = 1;
truncate table tipo_norma;
ALTER TABLE tipo_norma AUTO_INCREMENT = 1;